export const pgSql = (options) => {
  const { tableName, tableComment } = options;
  const { contentTem, commentsSql } = content(options);
  return `
-- Drop table if exists
DROP TABLE IF EXISTS "${tableName}";

-- Create table
CREATE TABLE "${tableName}" (
${contentTem}
);
${commentsSql}${tableComment ? `\nCOMMENT ON TABLE "${tableName}" IS '${escapeComment(tableComment)}';` : ''}
`.trim();
};

function content(options) {
  const { tableName, columns } = options;
  columns.sort((a, b) => b.isPk - a.isPk); // 保证主键始终在第一个

  const defs: string[] = [];
  const comments: string[] = [];

  columns.forEach((column) => {
    const { javaField, isPk, columnType, columnComment, isIncrement } = column;
    const field = convertToSnakeCase(javaField);

    if (isPk == '1') {
      let line = `  "${field}" ${mapColumnType(columnType)}`;
      if (isIncrement == '1') {
        line += ` GENERATED BY DEFAULT AS IDENTITY`;
      }
      line += ` NOT NULL`;
      if (columnComment) {
        comments.push(`COMMENT ON COLUMN "${tableName}"."${field}" IS '${escapeComment(columnComment)}';`);
      }
      line += `,\n  PRIMARY KEY ("${field}")`;
      defs.push(line);
    } else {
      let line = `  "${field}" ${mapColumnType(columnType)}`;
      const defaultVal = getColumnDefault(column);
      if (defaultVal !== undefined && defaultVal !== null && defaultVal !== '') {
        line += ` DEFAULT ${defaultVal}`;
      }
      if (columnComment) {
        comments.push(`COMMENT ON COLUMN "${tableName}"."${field}" IS '${escapeComment(columnComment)}';`);
      }
      defs.push(line);
    }
  });

  const contentTem = defs.join(',\n');
  const commentsSql = comments.length > 0 ? '\n' + comments.join('\n') : '';

  return { contentTem, commentsSql };
}

function convertToSnakeCase(str) {
  return str.replace(/([A-Z])/g, '_$1').toLowerCase();
}

function escapeComment(comment) {
  if (!comment) return '';
  return String(comment).replace(/'/g, "''");
}

// 规范化 PostgreSQL 类型名称
function mapColumnType(columnType) {
  if (!columnType) return 'varchar(255)';

  const type = columnType.toLowerCase();

  // 将 PostgreSQL 内部类型名映射为标准 SQL 类型名
  if (type === 'int4') return 'integer';
  if (type === 'int8') return 'bigint';
  if (type === 'int2') return 'smallint';
  if (type === 'float4') return 'real';
  if (type === 'float8') return 'double precision';
  if (type === 'bool') return 'boolean';
  if (type === 'timestamptz') return 'timestamp with time zone';
  if (type === 'timetz') return 'time with time zone';

  // varchar, char, numeric, decimal 等带参数的类型保持原样
  if (type.startsWith('varchar')) return type;
  if (type.startsWith('char')) return type;
  if (type.startsWith('numeric')) return type;
  if (type.startsWith('decimal')) return type;

  // 其他标准类型保持小写
  if (['integer', 'bigint', 'smallint', 'real', 'double precision', 'boolean',
       'text', 'timestamp', 'date', 'time', 'json', 'jsonb', 'uuid', 'bytea'].includes(type)) {
    return type;
  }

  // 默认返回原类型（小写）
  return columnType.toLowerCase();
}

// 字段默认值
function getColumnDefault(column) {
  let defaultValue = column.columnDefault;

  if (defaultValue === undefined || defaultValue === null) {
    return null;
  }

  // 转换为字符串处理
  defaultValue = String(defaultValue);

  // 移除 PostgreSQL 特有的类型转换后缀（如果已经存在）
  defaultValue = defaultValue.replace(/::\w+/g, '');

  const columnType = (column.columnType || '').toLowerCase();

  // 字符串类型需要用单引号包裹
  if (columnType === 'char' || columnType.startsWith('char(') ||
      columnType === 'varchar' || columnType.startsWith('varchar(') ||
      columnType === 'text') {
    // 转义单引号
    const escaped = defaultValue.replace(/'/g, "''");
    return `'${escaped}'`;
  }

  // 布尔类型
  if (columnType === 'bool' || columnType === 'boolean') {
    if (defaultValue === 'true' || defaultValue === '1' || defaultValue === 't') {
      return 'true';
    } else if (defaultValue === 'false' || defaultValue === '0' || defaultValue === 'f') {
      return 'false';
    }
  }

  // 数值类型、timestamp 等直接返回
  return defaultValue;
}
